[application]

[web.app]

# HTML title tag content
title = "Star Trek: Attack Wing"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
category = "BoardGame"
short_description = "Star Trek: Attack Wing"
long_description = "Star Trek: Attack Wing is a tactical space combat game set in the Star Trek universe. Players control ships from the Star Trek universe and engage in strategic battles."
