#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum ShipClass {
    MirandaClass,
    GalaxyClass,
    BorgSphere,
    AkiraClass,
    NeghvarClass,
    KTIngaClass,
    BRelClass,
    DefiantClass,
    KlingonBirdOfPrey,
    CardassianGalorClass,
    CardassianKeldonClass,
    DKyrClass,
    ConstitutionClass,
    ConstitutionClassKelvin,
    NebulaClass,
    D7Class,
    BorgScoutCube,
    IntrepidClass,
    DauntlessClass,
    VidiianBattleCruiser,
    AndorianBattleCruiser,
    MaquisRaider,
    MaquisRaiderB,
    WarbirdClass,
    FederationAttackSquadron,
    HirogenWarship,
    JemHadarAttackShip,
    GornRaider,
    DKoraClass,
    FerengiShuttle,
    BorgOctahedron,
    JemHadarBattleship,
    ValdoreClass,
    RomulanScienceVessel,
    BreenBattleCruiser,
    NorClassOrbitalSpaceStation,
    DDeridexClass,
    RomulanBirdOfPrey,
    KVortClass,
    Koranak,
    ExcelsiorClass,
    RomulanScoutVessel,
    NovaClass,
    RaptorClass,
    BajoranScoutShip,
    HidekiClassAttackSquadron,
    KazonRaider,
    Species8472Bioship,
    TholianVessel,
    BajoranInterceptor,
    BorgTacticalCube,
    Saber,
    JemHadarBattleCruiser,
    VorChaClass,
    RomulanDroneShip,
    CardassianAtr4107,
    OberthClass,
    DeltaFlyerClassShuttlecraft,
    XindiReptilianWarship,
    XindiAquaticCruiser,
    XindiInsectoidStarship,
    ConstitutionRefitClass,
    BorgCube,
    XindiWeapon,
    ScorpionClassAttackSquadron,
    BajoranSolarSailor,
    ConstellationClass,
    BorgType03,
    SuurokClass,
    AerieClass,
    FederationNXClass,
    GalaxyClassMU,
    PredatorClass,
    SovereignClass,
    DefiantClassMirror,
    RemanWarbird,
    NeghVarClassMirror,
    Type7Shuttlecraft,
    TerranNXClass,
    KrenimWeaponShip,
    PrometheusClass,
    OlympicClass,
}

impl ShipClass {
    pub fn name(&self) -> &'static str {
        match self {
            ShipClass::MirandaClass => "Miranda Class",
            ShipClass::GalaxyClass => "Galaxy Class",
            ShipClass::BorgSphere => "Borg Sphere",
            ShipClass::AkiraClass => "Akira Class",
            ShipClass::NeghvarClass => "Negh'var Class",
            ShipClass::KTIngaClass => "K'T'Inga Class",
            ShipClass::BRelClass => "B'Rel Class",
            ShipClass::DefiantClass => "Defiant Class",
            ShipClass::KlingonBirdOfPrey => "Klingon Bird-of-Prey",
            ShipClass::CardassianGalorClass => "Cardassian Galor Class",
            ShipClass::CardassianKeldonClass => "Cardassian Keldon Class",
            ShipClass::DKyrClass => "D'Kyr Class",
            ShipClass::ConstitutionClass => "Constitution Class",
            ShipClass::ConstitutionClassKelvin => "Constitution Class (Kelvin)",
            ShipClass::NebulaClass => "Nebula Class",
            ShipClass::D7Class => "D7 Class",
            ShipClass::BorgScoutCube => "Borg Scout Cube",
            ShipClass::IntrepidClass => "Intrepid Class",
            ShipClass::DauntlessClass => "Dauntless Class",
            ShipClass::VidiianBattleCruiser => "Vidiian Battle Cruiser",
            ShipClass::AndorianBattleCruiser => "Andorian Battle Cruiser",
            ShipClass::MaquisRaider => "Maquis Raider",
            ShipClass::MaquisRaiderB => "Maquis Raider",
            ShipClass::WarbirdClass => "Warbird Class",
            ShipClass::FederationAttackSquadron => "Federation Attack Squadron",
            ShipClass::HirogenWarship => "Hirogen Warship",
            ShipClass::JemHadarAttackShip => "Jem'Hadar Attack Ship",
            ShipClass::GornRaider => "Gorn Raider",
            ShipClass::DKoraClass => "D'Kora Class",
            ShipClass::FerengiShuttle => "Ferengi Shuttle",
            ShipClass::BorgOctahedron => "Borg Octahedron",
            ShipClass::JemHadarBattleship => "Jem'Hadar Battleship",
            ShipClass::ValdoreClass => "Valdore Class",
            ShipClass::RomulanScienceVessel => "Romulan Science Vessel",
            ShipClass::BreenBattleCruiser => "Breen Battle Cruiser",
            ShipClass::NorClassOrbitalSpaceStation => "Nor Class Orbital Space Station",
            ShipClass::DDeridexClass => "D'deridex Class",
            ShipClass::RomulanBirdOfPrey => "Romulan Bird-of-Prey",
            ShipClass::KVortClass => "K'Vort Class",
            ShipClass::Koranak => "Koranak",
            ShipClass::ExcelsiorClass => "Excelsior Class",
            ShipClass::RomulanScoutVessel => "Romulan Scout Vessel",
            ShipClass::NovaClass => "Nova Class",
            ShipClass::RaptorClass => "Raptor Class",
            ShipClass::BajoranScoutShip => "Bajoran Scout Ship",
            ShipClass::HidekiClassAttackSquadron => "Hideki Class Attack Squadron",
            ShipClass::KazonRaider => "Kazon Raider",
            ShipClass::Species8472Bioship => "Species 8472 Bioship",
            ShipClass::TholianVessel => "Tholian Vessel",
            ShipClass::BajoranInterceptor => "Bajoran Interceptor",
            ShipClass::BorgTacticalCube => "Borg Tactical Cube",
            ShipClass::Saber => "Saber Class",
            ShipClass::JemHadarBattleCruiser => "Jem'Hadar Battle Cruiser",
            ShipClass::VorChaClass => "Vor'cha Class",
            ShipClass::RomulanDroneShip => "Romulan Drone Ship",
            ShipClass::CardassianAtr4107 => "Cardassian ATR-4107",
            ShipClass::OberthClass => "Oberth Class",
            ShipClass::DeltaFlyerClassShuttlecraft => "Delta Flyer Class Shuttlecraft",
            ShipClass::XindiReptilianWarship => "Xindi Reptilian Warship",
            ShipClass::XindiAquaticCruiser => "Xindi Aquatic Cruiser",
            ShipClass::XindiInsectoidStarship => "Xindi Insectoid Starship",
            ShipClass::ConstitutionRefitClass => "Constitution Refit Class",
            ShipClass::BorgCube => "Borg Cube",
            ShipClass::XindiWeapon => "Xindi Weapon",
            ShipClass::ScorpionClassAttackSquadron => "Scorpion Class Attack Squadron",
            ShipClass::BajoranSolarSailor => "BAJORAN SOLAR SAILOR",
            ShipClass::ConstellationClass => "Constellation Class",
            ShipClass::BorgType03 => "Borg Type 03",
            ShipClass::SuurokClass => "Suurok Class",
            ShipClass::AerieClass => "Aerie Class",
            ShipClass::FederationNXClass => "Federation NX Class",
            ShipClass::GalaxyClassMU => "Galaxy Class (MU)",
            ShipClass::PredatorClass => "Predator Class",
            ShipClass::SovereignClass => "Sovereign Class",
            ShipClass::DefiantClassMirror => "Defiant Class (Mirror)",
            ShipClass::RemanWarbird => "Reman Warbird",
            ShipClass::NeghVarClassMirror => "Negh'var Class (Mirror)",
            ShipClass::Type7Shuttlecraft => "Type 7 Shuttlecraft",
            ShipClass::TerranNXClass => "Terran NX Class",
            ShipClass::KrenimWeaponShip => "Krenim Weapon Ship",
            ShipClass::PrometheusClass => "Prometheus Class",
            ShipClass::OlympicClass => "Olympic Class",
        }
    }
}