use crate::game::factions::{ActionType, ShipSpecialAbility, ShipType, StawFaction, StawShipArchetype, UpgradeType};

pub const SHIPS: &'static [StawShipArchetype] = &[
    StawShipArchetype {
        name: "Deep Space 9",
        unique: true,
        class: "Nor Class Orbital Space Station",
        factions: &[StawFaction::Federation, StawFaction::Bajoran],
        primary_weapon: 5,
        agility: 0,
        hull: 8,
        shields: 8,
        ship_type: ShipType::DeepSpace9,
        upgrade_bar: &[],
        special_ability_description: concat!(
            "Each time you defend, during the Roll Defense Dice step, you may roll up to ",
            "2 additional defense dice.  If you do, disable 1 of your Active Shields for ",
            "each additional die you roll."),
        special_ability: ShipSpecialAbility::DeepSpace9_1,
        action_bar: &[
            ActionType::AcquireTargetLock,
            ActionType::Scan,
            ActionType::BattleStations,
        ],
        squad_point_cost: 44,
    },
    StawShipArchetype {
        name: "Deep Space 9",
        unique: true,
        class: "Nor Class Orbital Space Station",
        factions: &[StawFaction::Federation, StawFaction::Bajoran],
        primary_weapon: 5,
        agility: 0,
        hull: 8,
        shields: 8,
        ship_type: ShipType::DeepSpace9,
        upgrade_bar: &[UpgradeType::Weapon, UpgradeType::Weapon, UpgradeType::Weapon, UpgradeType::Crew, UpgradeType::Crew, UpgradeType::Crew],
        special_ability_description: "When firing any torpedoes, do not disable the torpedoes.",
        special_ability: ShipSpecialAbility::DeepSpace9_2,
        action_bar: &[
            ActionType::AcquireTargetLock,
            ActionType::Scan,
            ActionType::BattleStations,
        ],
        squad_point_cost: 44,
    },
    StawShipArchetype {
        name: "U.S.S. Voyager",
        unique: true,
        class: "Intrepid Class",
        factions: &[
            StawFaction::Federation,
            StawFaction::Borg,
        ],
        primary_weapon: 5,
        agility: 2,
        hull: 4,
        shields: 6,
        ship_type: ShipType::UssVoyager,
        upgrade_bar: &[
            UpgradeType::Borg,
            UpgradeType::Tech,
            UpgradeType::Weapon,
            UpgradeType::Crew,
            UpgradeType::Crew,
        ],
        special_ability_description: concat!("Free action: ",
        "If this ship performed a Green Maneuver this game round: Perform a <AcquireTargetLock> action as a Free Action."),
        special_ability: ShipSpecialAbility::DeepSpace9_1,
        action_bar: &[
            ActionType::EvasiveManeuvers,
            ActionType::AcquireTargetLock,
            ActionType::Scan,
            ActionType::BattleStations,
        ],
        squad_point_cost: 34,
    },
    StawShipArchetype {
        name: "U.S.S. Enterprise-E",
        unique: true,
        class: "Sovereign Class",
        factions: &[StawFaction::Federation],
        primary_weapon: 5,
        agility: 1,
        hull: 5,
        shields: 5,
        ship_type: ShipType::EnterpriseE,
        upgrade_bar: &[
            UpgradeType::Tech,
            UpgradeType::Weapon,
            UpgradeType::Weapon,
            UpgradeType::Crew,
            UpgradeType::Crew,
        ],
        special_ability_description: concat!("You may fire a torpedo at an enemy ship without ",
        "needing a target lock. If you do so, place an Auxiliary Power Token beside your ship."),
        special_ability: ShipSpecialAbility::DeepSpace9_1,
        action_bar: &[],
        squad_point_cost: 0,
    }
];